##Pandas Recap

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)
root_path = 'gdrive/My Drive'

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [ ]:
import pandas as pd
data = pd.read_csv(root_path+'/mobile_data.csv',index_col=0)

In [ ]:
print(data)

         Pixel Density  Screen Size  Weight  ...  Sim1_3G  Sim1_4G  Rating
PhoneId                                      ...                          
0                  403         6.26     182  ...        0        1     4.5
1                  271         6.20     168  ...        0        1     4.5
2                  409         6.30     168  ...        0        1     4.4
4                  411         6.00     169  ...        0        1     4.3
5                  396         6.50     175  ...        0        1     4.4
...                ...          ...     ...  ...      ...      ...     ...
465                220         5.00     141  ...        0        1     3.8
466                401         5.50     165  ...        0        1     3.9
468                282         5.20     160  ...        0        1     4.1
470                218         4.50     156  ...        0        1     3.6
472                401         5.50     153  ...        0        1     4.3

[341 rows x 87 columns]


# Checking Datatypes

In [ ]:
data.dtypes

Pixel Density                    int64
Screen Size                    float64
Weight                           int64
RAM                              int64
Processor_frequency            float64
                                ...   
SIM Slot(s)_Single SIM, GSM      int64
Sim1_2G                          int64
Sim1_3G                          int64
Sim1_4G                          int64
Rating                         float64
Length: 87, dtype: object

In [ ]:
#Count of unique data types
data.get_dtype_counts()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: `get_dtype_counts` has been deprecated and will be removed in a future version. For DataFrames use `.dtypes.value_counts()
  """Entry point for launching an IPython kernel.


float64     5
int64      82
dtype: int64

#Selecting data based on data types
pandas.DataFrame.select_dtypes() returns a subset of the columns from dataframe based on the column dtypes

In [ ]:
data_fil = data.select_dtypes(exclude=[object])

In [ ]:
print(data_fil)

         Pixel Density  Screen Size  Weight  ...  Sim1_3G  Sim1_4G  Rating
PhoneId                                      ...                          
0                  403         6.26     182  ...        0        1     4.5
1                  271         6.20     168  ...        0        1     4.5
2                  409         6.30     168  ...        0        1     4.4
4                  411         6.00     169  ...        0        1     4.3
5                  396         6.50     175  ...        0        1     4.4
...                ...          ...     ...  ...      ...      ...     ...
465                220         5.00     141  ...        0        1     3.8
466                401         5.50     165  ...        0        1     3.9
468                282         5.20     160  ...        0        1     4.1
470                218         4.50     156  ...        0        1     3.6
472                401         5.50     153  ...        0        1     4.3

[341 rows x 87 columns]


#Summary of Dataframe
Details about the data present in the dataframe maybe obtained using info function

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341 entries, 0 to 472
Data columns (total 87 columns):
Pixel Density                                341 non-null int64
Screen Size                                  341 non-null float64
Weight                                       341 non-null int64
RAM                                          341 non-null int64
Processor_frequency                          341 non-null float64
Screen to Body Ratio (calculated)            341 non-null float64
Height                                       341 non-null float64
Internal Memory                              341 non-null int64
Capacity                                     341 non-null int64
Resolution                                   341 non-null int64
SIM 2_2G                                     341 non-null int64
SIM 2_3G                                     341 non-null int64
SIM 2_4G                                     341 non-null int64
SIM 2_Other                                  341 non-nu

#Analysis of Data in a Field

To understand the datatype chosen by Pandas, let us look at the unique  elements of columns

In [ ]:
#unique() of NumPyis used to find the unique elements of a column
import numpy as np
np.unique(data['Rating'])

array([2.5, 2.8, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ,
       4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 5. ])

In [ ]:
np.unique(data['Sim1_3G'])

array([0, 1])

In [ ]:
np.unique(data['Height'])

array([115.6       , 116.4       , 117.5       , 118.        ,
       120.        , 122.9       , 123.        , 123.8       ,
       124.        , 124.5       , 125.        , 126.8       ,
       128.        , 130.        , 130.7       , 132.        ,
       132.7       , 132.9       , 133.4       , 133.6       ,
       134.        , 135.        , 136.5       , 137.1       ,
       138.1       , 138.3       , 138.4       , 140.4       ,
       141.5       , 141.6       , 141.9       , 142.1       ,
       142.3       , 142.4       , 142.5       , 142.7       ,
       142.8       , 143.        , 143.1       , 143.5       ,
       143.6       , 143.8       , 144.        , 144.2       ,
       144.3       , 144.5       , 144.7       , 144.8       ,
       145.        , 145.2       , 145.4       , 145.5       ,
       145.6       , 145.8       , 146.        , 146.2       ,
       146.5       , 146.8       , 147.        , 147.2       ,
       147.3       , 147.5       , 147.6       , 147.7 

In [ ]:
print(np.unique(data['SIM Slot(s)_Dual SIM, GSM+CDMA']))

[0 1]


In [ ]:
print(np.unique(data['Resolution']))

[ 2  5  7  8 12 13 16 20 24 25]


In [ ]:
print(np.unique(data['Capacity']))

[ 1020  1100  1200  1300  1400  1500  1600  1642  1700  1715  1800  1810
  1821  1850  1960  2000  2050  2070  2150  2300  2350  2400  2420  2470
  2500  2550  2600  2620  2630  2670  2675  2700  2716  2730  2750  2770
  2800  2850  2900  2915  2942  2965  2990  3000  3010  3020  3050  3055
  3060  3080  3090  3100  3174  3180  3200  3225  3260  3300  3340  3360
  3400  3410  3430  3450  3500  3510  3520  3600  3700  3730  3750  3800
  4000  4010  4030  4050  4070  4100  4200  4230  4550  5000  5020  5100
  5300 13000]


In [ ]:
print(np.unique(data['Internal Memory']))

[  0   4   8  16  32  64 128 256 512]


## Since values five, four and three are read as strings, datatype is treated as object instead of integer

#Handling Missing Values

1.   Missing values exist in the form of 'nan', '??', '????'
2.   Python by default replace blank with 'nan'



In [ ]:
data = pd.read_csv(root_path+'/mobile_data.csv',index_col=0,na_values=["??","???"])

In [ ]:
print(data)

         Pixel Density  Screen Size  Weight  ...  Sim1_3G  Sim1_4G  Rating
PhoneId                                      ...                          
0                  403         6.26     182  ...        0        1     4.5
1                  271         6.20     168  ...        0        1     4.5
2                  409         6.30     168  ...        0        1     4.4
4                  411         6.00     169  ...        0        1     4.3
5                  396         6.50     175  ...        0        1     4.4
...                ...          ...     ...  ...      ...      ...     ...
465                220         5.00     141  ...        0        1     3.8
466                401         5.50     165  ...        0        1     3.9
468                282         5.20     160  ...        0        1     4.1
470                218         4.50     156  ...        0        1     3.6
472                401         5.50     153  ...        0        1     4.3

[341 rows x 87 columns]


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341 entries, 0 to 472
Data columns (total 87 columns):
Pixel Density                                341 non-null int64
Screen Size                                  341 non-null float64
Weight                                       341 non-null int64
RAM                                          341 non-null int64
Processor_frequency                          341 non-null float64
Screen to Body Ratio (calculated)            341 non-null float64
Height                                       341 non-null float64
Internal Memory                              341 non-null int64
Capacity                                     341 non-null int64
Resolution                                   341 non-null int64
SIM 2_2G                                     341 non-null int64
SIM 2_3G                                     341 non-null int64
SIM 2_4G                                     341 non-null int64
SIM 2_Other                                  341 non-nu

# Changing datatype
astype() method is used to explicitly convert data types from one to another

In [ ]:
# Changing 'MetColor' and 'Automatic' to object data type
data['Capacity'] = data['Capacity'].astype('object')

In [ ]:
# Changing 'MetColor' and 'Automatic' to object data type
data['Resolution'] = data['Resolution'].astype('object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341 entries, 0 to 472
Data columns (total 87 columns):
Pixel Density                                341 non-null int64
Screen Size                                  341 non-null float64
Weight                                       341 non-null int64
RAM                                          341 non-null int64
Processor_frequency                          341 non-null float64
Screen to Body Ratio (calculated)            341 non-null float64
Height                                       341 non-null float64
Internal Memory                              341 non-null int64
Capacity                                     341 non-null object
Resolution                                   341 non-null object
SIM 2_2G                                     341 non-null int64
SIM 2_3G                                     341 non-null int64
SIM 2_4G                                     341 non-null int64
SIM 2_Other                                  341 non-

# Category Vs Object Datatype
Memory consumed can be checked with nbytes

In [ ]:
data['Resolution'].nbytes

2728

In [ ]:
data['Resolution'].astype('category').nbytes # will not make changes

421

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341 entries, 0 to 472
Data columns (total 87 columns):
Pixel Density                                341 non-null int64
Screen Size                                  341 non-null float64
Weight                                       341 non-null int64
RAM                                          341 non-null int64
Processor_frequency                          341 non-null float64
Screen to Body Ratio (calculated)            341 non-null float64
Height                                       341 non-null float64
Internal Memory                              341 non-null int64
Capacity                                     341 non-null object
Resolution                                   341 non-null object
SIM 2_2G                                     341 non-null int64
SIM 2_3G                                     341 non-null int64
SIM 2_4G                                     341 non-null int64
SIM 2_Other                                  341 non-

In [ ]:
data['Resolution'] = data['Resolution'].astype('category') # datatype of FuelType is changed

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341 entries, 0 to 472
Data columns (total 87 columns):
Pixel Density                                341 non-null int64
Screen Size                                  341 non-null float64
Weight                                       341 non-null int64
RAM                                          341 non-null int64
Processor_frequency                          341 non-null float64
Screen to Body Ratio (calculated)            341 non-null float64
Height                                       341 non-null float64
Internal Memory                              341 non-null int64
Capacity                                     341 non-null object
Resolution                                   341 non-null category
SIM 2_2G                                     341 non-null int64
SIM 2_3G                                     341 non-null int64
SIM 2_4G                                     341 non-null int64
SIM 2_Other                                  341 no

#Replacing values in dataframe with desired values

In [ ]:
data['Internal Memory'].replace('64',128,inplace=True)
data['Internal Memory'].replace('32',32,inplace=True)
data['Internal Memory'].replace('128',64,inplace=True)


In [ ]:
data['Internal Memory']=data['Internal Memory'].astype('int64')

In [ ]:
print(data)

         Pixel Density  Screen Size  Weight  ...  Sim1_3G  Sim1_4G  Rating
PhoneId                                      ...                          
0                  403         6.26     182  ...        0        1     4.5
1                  271         6.20     168  ...        0        1     4.5
2                  409         6.30     168  ...        0        1     4.4
4                  411         6.00     169  ...        0        1     4.3
5                  396         6.50     175  ...        0        1     4.4
...                ...          ...     ...  ...      ...      ...     ...
465                220         5.00     141  ...        0        1     3.8
466                401         5.50     165  ...        0        1     3.9
468                282         5.20     160  ...        0        1     4.1
470                218         4.50     156  ...        0        1     3.6
472                401         5.50     153  ...        0        1     4.3

[341 rows x 87 columns]


# Identify Missing Values in a column

In [ ]:
data.isnull().sum()

Pixel Density                  0
Screen Size                    0
Weight                         0
RAM                            0
Processor_frequency            0
                              ..
SIM Slot(s)_Single SIM, GSM    0
Sim1_2G                        0
Sim1_3G                        0
Sim1_4G                        0
Rating                         0
Length: 87, dtype: int64