##SVM

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload() 

Saving car.data to car (1).data


In [ ]:
df = pd.read_csv('car.data',
names=['buying','maintenance','doors','persons','lug_boot','safety','p_class'])

In [ ]:
df.head(10)

buying maintenance doors persons lug_boot safety p_class
0  vhigh       vhigh     2       2    small    low   unacc
1  vhigh       vhigh     2       2    small    med   unacc
2  vhigh       vhigh     2       2    small   high   unacc
3  vhigh       vhigh     2       2      med    low   unacc
4  vhigh       vhigh     2       2      med    med   unacc
5  vhigh       vhigh     2       2      med   high   unacc
6  vhigh       vhigh     2       2      big    low   unacc
7  vhigh       vhigh     2       2      big    med   unacc
8  vhigh       vhigh     2       2      big   high   unacc
9  vhigh       vhigh     2       4    small    low   unacc

In [ ]:
df = df.replace(to_replace =["vhigh", "4", "vgood"], value = 4 )
df = df.replace(to_replace =["high", "3", "big", "good"], value = 3 )
df = df.replace(to_replace =["med", "2", "acc"], value = 2 )
df = df.replace(to_replace =["unacc", "small", "low"], value = 1)
df = df.replace(to_replace =["5more","more"], value = 5)

In [ ]:
df.head(100)

buying  maintenance  doors  persons  lug_boot  safety  p_class
0        4            4      2        2         1       1        1
1        4            4      2        2         1       2        1
2        4            4      2        2         1       3        1
3        4            4      2        2         2       1        1
4        4            4      2        2         2       2        1
..     ...          ...    ...      ...       ...     ...      ...
95       4            4      5        4         2       3        1
96       4            4      5        4         3       1        1
97       4            4      5        4         3       2        1
98       4            4      5        4         3       3        1
99       4            4      5        5         1       1        1

[100 rows x 7 columns]

In [ ]:
df['safety']

0       1
1       2
2       3
3       1
4       2
       ..
1723    2
1724    3
1725    1
1726    2
1727    3
Name: safety, Length: 1728, dtype: int64

In [ ]:
X = df.drop(['safety'],axis=1)
y = df['safety']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear', degree=8)
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
y_test.value_counts()

2    121
1    115
3    110
Name: safety, dtype: int64

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[115   0   0]
 [ 75  34  12]
 [ 50  24  36]]
              precision    recall  f1-score   support

           1       0.48      1.00      0.65       115
           2       0.59      0.28      0.38       121
           3       0.75      0.33      0.46       110

    accuracy                           0.53       346
   macro avg       0.61      0.54      0.49       346
weighted avg       0.60      0.53      0.49       346

